// <auto-generated />
using System;
using FinFamilia.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinFamilia.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307185537_FixModelChanges")]
    partial class FixModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("FinFamilia.Api.Models.Cartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bandeira")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Fechamento")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Limite")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Vencimento")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cartoes");
                });

            modelBuilder.Entity("FinFamilia.Api.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("FinFamilia.Api.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataCompra")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataInicioRecorrencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Parcelas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Recorrente")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("FinFamilia.Api.Models.CompraPessoa", b =>
                {
                    b.Property<int>("CompraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PessoaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorRateio")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("CompraId", "PessoaId");

                    b.HasIndex("PessoaId");

                    b.ToTable("CompraPessoas");
                });

            modelBuilder.Entity("FinFamilia.Api.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("FinFamilia.Api.Models.Compra", b =>
                {
                    b.HasOne("FinFamilia.Api.Models.Cartao", "Cartao")
                        .WithMany("Compras")
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinFamilia.Api.Models.Categoria", "Categoria")
                        .WithMany("Compras")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cartao");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("FinFamilia.Api.Models.CompraPessoa", b =>
                {
                    b.HasOne("FinFamilia.Api.Models.Compra", "Compra")
                        .WithMany("CompraPessoas")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinFamilia.Api.Models.Pessoa", "Pessoa")
                        .WithMany("CompraPessoas")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("FinFamilia.Api.Models.Cartao", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("FinFamilia.Api.Models.Categoria", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("FinFamilia.Api.Models.Compra", b =>
                {
                    b.Navigation("CompraPessoas");
                });

            modelBuilder.Entity("FinFamilia.Api.Models.Pessoa", b =>
                {
                    b.Navigation("CompraPessoas");
                });
#pragma warning restore 612, 618
        }
    }
}
